language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "w74qPOeZBOq87zx0dTgGDZolWaxohUUGwatv4Xb5BrGPmSNd7jTvg+hCx/A/ZbLbdT3wdRCPNZ3+Vyi1WsW2KEERq7rThWdkVbzKSiDODHQ5jAyTYLwLGD4C8VmnOOPw2BcRmJQZDZCSvnIXVJ3ozYaGfP/8SqArsDBNdwZJ35EOdBfgbk98e2Fy7BUnoiGy+0Jc769OLwzNe65326Fcjlqx/RtCyC5rCUJOeOKwVOje7tAHaMg+kzlzlLocsilQc1uDNWH8fa0ScqCyBZnwwmIEtbXPB3pscJe5B5Fsd3hXKTJCicChlwINLWJx5SFyZ1CKgasVvrRZxnw7+YyjApaT40xV4yWGVhRtCGS8Rir+ph9IRxzAR0aElVdYLxnOZ91LrE8VpT3NmUcp5RuwxG7ELCLpgaRm39VzSC33cvtBTW2X6T5vQkmwOxxowMXy09H90pp7spbUk/ScfibzR3zs/jyGE6POx4AXqQnXcEVt1OPfmfiqy/lccBJw5DKiovGLg2MNfuHwfb1Rn7Pra9zKglT6+90evEt8Nj4g+jzSOyAoy3sYzkvUtEKCHhnqKnaGb2FqiGPG5iKeKSqm4xuoVWf3pVq+Ym8KmnQhKtXPiEOBjAzxRhrHU5Hu/Xq+Wwmj062BTyqF734AUa8mcKcx8ZroTqWKAspT9APNg5A="  
  app: tasktictactoe-staging
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_deploy:
  - ./gradlew seleniumXvfb
  deploy:
    provider: heroku
    api_key:
      secure: E0b3LLQQ1uFzBmaxj44m7YMlRv0dQhk87xmvXHJhpmZHXGLo48yLBRYWFnlUuwAbtq0YoTG5TR++ScO6GsrJ5YQ/RKToJTYB2j/mTGUsbOF4KNU6LquLJlLoEQtJnL2sQ59IZp2z7eG0G/xbZR7y31i22Zqe/iUgafomXMXWZ2HVnvgK2nonjwp5yZqwsfy+gGWrRQWCicHQvsj0++rhB1FBSIsxSVV8JWGOp6TpAKRjqKB4HmDTfgraN5EF87dOcTU65ExSJ74g8ffeMHK1opyARcWf0CZBkZxZSVXyK5Ip2jGT5QPDF7s5x/7ohVpI17tOmJ69z7MtrELtFwIe/R3YGwwOfQvjjX6Qcxme21eucFWamwk0HJLAr635bqrzQd8qlAOFBGNHMmtWoSgfDiANuAcfupy5jpP9YBNQPwslbWCWOacxFNxoL4rKk7SfLqMYlsXobLTGpWY/F3HVjJC+2iko7cgwuCJhovaBDeuuZ9pmlOowy58RE48kDGV7ul0MlmXcpVlRXp97UPX0w0lSk/kG7+Hi66HpxRWbC/YGJSjJyuZpK2LmOH26nrmBAP/DMcavUHsIkhpAyleNwjm3jfNOwHUXaJmrfMSiX/mxH08B8NetPTCH5YN4XhS2TI89tphXOYc9nLOss72+HTvskxUa0u6MSdh+LTpPG0o=
    app: tasktictactoe
