language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: OPQVQCCV2I9dCrxuliyLIhu92BZ9oZrYILFHFAJPpHO6JmiciTT4WdED/bTGnxVduzCyeVoe5puXbGegYRKHRutj3DCDYsgOB8V4O9OCnCpItDlddP7MMW2+RyYNcp6jM66ydR5lJ70UUV48PNLNijsWHtsJX6OUAAK/0uPbjQo17LzaRFlNCm+WtSu71MbJ78rmWWkFYBlcVfsneSYVJm2sLhRMZcWjpukIbWbjCCigSLIsSA3WBshiNg07UWJbv/1BCVxuX5hYaHkXO1hFAYorMTtTXZwO4/9LOrNwU13Vt4AvScPoRaqe7bdUUuCbxc6oE6VeCA9+7Yg8+wyTEnTpQLQutMANurlubESWJuiqSHCTBH81zH7UzYOUeuJAnGNQMTN/DwPNzYG2czaBhKKEKi63n5VGiKlUy1jRvbpr9JyDTl21MkZUXS+/wroGRGaT+ETjq1g8lE3zFga4Qy5qTqCJUYE+JjwzrrTXH2k1HErOTSPZjYcHnpaEIrMwDyPOhkqF7VPvI0qZXYPphHUS9MACG523oWkQyg0l4sbbv2Jh3+Llsc9ukzWY2KIW0Q5vAqt65snA42Ws6GbtT4YBDUCrp0CVSS1IFyDlfIlCNHhAoBWD5nHtkDhLYrsbRHc9x83IBAI06UGiQYTR2o8cOUOuusGroqBQEuH/hlg=
  app: webdevalli
