language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  on: production
  api_key:
    master:
     secure: E0b3LLQQ1uFzBmaxj44m7YMlRv0dQhk87xmvXHJhpmZHXGLo48yLBRYWFnlUuwAbtq0YoTG5TR++ScO6GsrJ5YQ/RKToJTYB2j/mTGUsbOF4KNU6LquLJlLoEQtJnL2sQ59IZp2z7eG0G/xbZR7y31i22Zqe/iUgafomXMXWZ2HVnvgK2nonjwp5yZqwsfy+gGWrRQWCicHQvsj0++rhB1FBSIsxSVV8JWGOp6TpAKRjqKB4HmDTfgraN5EF87dOcTU65ExSJ74g8ffeMHK1opyARcWf0CZBkZxZSVXyK5Ip2jGT5QPDF7s5x/7ohVpI17tOmJ69z7MtrELtFwIe/R3YGwwOfQvjjX6Qcxme21eucFWamwk0HJLAr635bqrzQd8qlAOFBGNHMmtWoSgfDiANuAcfupy5jpP9YBNQPwslbWCWOacxFNxoL4rKk7SfLqMYlsXobLTGpWY/F3HVjJC+2iko7cgwuCJhovaBDeuuZ9pmlOowy58RE48kDGV7ul0MlmXcpVlRXp97UPX0w0lSk/kG7+Hi66HpxRWbC/YGJSjJyuZpK2LmOH26nrmBAP/DMcavUHsIkhpAyleNwjm3jfNOwHUXaJmrfMSiX/mxH08B8NetPTCH5YN4XhS2TI89tphXOYc9nLOss72+HTvskxUa0u6MSdh+LTpPG0o=
    production:
      secure: T13snyKqK1MxrucPyB7zm5Nha8JVbpc51eXyOIcDbEJXV4IQaDx6Te/oftgfrgjE8AxhYd+zvuDqkuqVNjYG0AJ/agVoNtT6NuZKXIvtbkdmD0CnEazMmRk08ysaJtaEBw55Un+s3Tq0sNelZc0cUtvc5krEt56oAyOJvKi/GdUqw5lHi121YorStGbY82vYzSqt8K50OTuR7ok5rT94jkRP/oHJsyIrSXiop6sFdXDt65zO9PDOSR8TdLbJE2nRAxmXKmCthvm1/3pxLVrx+tg+mrtihjZALg6z0IOB0IO2SuvXu2ioxaiKjOt4uh6YCd/iXevS9h9Hg44NH2g/NBvJONv0YoXsrVKE9J1G5HeSfxckXBGzp/uYwNOiNtYVgTWSQn2/A6W8jpbV8S5SdT28sNZ0Ca6DkdrsY0bL6Iq8Z2QjQEMLyjlkyQAvZV2//93ZrH55sIco6ndorF+r9ss4HUjFDnkKWg+tFHgVa2m5cTqN5xTLy9GXILdLoVZf7RiZzIbFdTGroDkoze1uc170hOzHQ8qMC/32WWAHJOMVmRzot7tmLLQMrBiybLf9B5KrXHReQU4/vTi3amYVRlOKdMjQnDk5dmWp4x2wrm/9FITjzetM7X4QXgqQJCVLzdGNj/lFk7ZEH5x6CzrDTfzaV7pYod+GxnPcvEOxMZo=
  app: 
    master: tasktictactoe
    production: webdevalli
