language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  on: production
  api_key:
  	master:
      secure: E0b3LLQQ1uFzBmaxj44m7YMlRv0dQhk87xmvXHJhpmZHXGLo48yLBRYWFnlUuwAbtq0YoTG5TR++ScO6GsrJ5YQ/RKToJTYB2j/mTGUsbOF4KNU6LquLJlLoEQtJnL2sQ59IZp2z7eG0G/xbZR7y31i22Zqe/iUgafomXMXWZ2HVnvgK2nonjwp5yZqwsfy+gGWrRQWCicHQvsj0++rhB1FBSIsxSVV8JWGOp6TpAKRjqKB4HmDTfgraN5EF87dOcTU65ExSJ74g8ffeMHK1opyARcWf0CZBkZxZSVXyK5Ip2jGT5QPDF7s5x/7ohVpI17tOmJ69z7MtrELtFwIe/R3YGwwOfQvjjX6Qcxme21eucFWamwk0HJLAr635bqrzQd8qlAOFBGNHMmtWoSgfDiANuAcfupy5jpP9YBNQPwslbWCWOacxFNxoL4rKk7SfLqMYlsXobLTGpWY/F3HVjJC+2iko7cgwuCJhovaBDeuuZ9pmlOowy58RE48kDGV7ul0MlmXcpVlRXp97UPX0w0lSk/kG7+Hi66HpxRWbC/YGJSjJyuZpK2LmOH26nrmBAP/DMcavUHsIkhpAyleNwjm3jfNOwHUXaJmrfMSiX/mxH08B8NetPTCH5YN4XhS2TI89tphXOYc9nLOss72+HTvskxUa0u6MSdh+LTpPG0o=
    production:
      secure: DLCMfvmdsTOhYpLkKSQLeUK4RQAXwh2DOO815Ml/pf4idG8sVJO9/HqUjqEEzLE9oxMp/2x7EdPfJ7MHuNp+uFitd/FgsEic5FCJqp+MYBVMaptVK/8bA4gbIV6gZRbZbCJbEikJvVCBmVveqf1EK+DKKhZD1QDIx/1Js0rKVPoiWno6Fua1f36Z95/jpcQIU+Q+elWQnnCIMGP2pUMgZ3UQH9F993LZBvfPcUUT7a/EmwvG0QJ8Id7VP+sm+ZK+RO2YLvmzV+LP9icR45KAVS8YpdMJSd/bKhKMjCRHmdDf/1nq2MGom+EIZqYobdUaoDWCwHW/o1/ges9xg756KjXSTaQEZHDTs0BOtsMwQHDHdfD8u89pz9G1BK6i0ZljN8R4x5JqW5gFlC1cM9cUhV2hox3DWEGAuOY/RGwAo/STARO9J4mGT/xy+xOOdAeKugQ4VJ891d5rS9fjNuIEdYHcfXzeoufNCQNiKFqYPXTptXZ/uTP6Tq3xcxdFIdzQUinp/jXeSMB3y0AbNHsN8EXauYkmv9PESa/wxpQdv5IKC3936t+rLip4sTfYDpyL03xKjDqLa0CL42sp//aAL1cO0+KURA6Orgw02493cxJnx+AldyDb1HmlCc8cAM8ewOJhhS7Lgo1aNDoq8te7ZJeTuJTmCVu2gwAnuBH8rXU=
  app: 
  	master: tasktictactoe
  	production: webDevPandas
